<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
        <LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>
	<ItemGroup>
		<EmbeddedResource Include="Shaders\Common\SFTemplate.hlsl" />
		<EmbeddedResource Include="Shaders\Standard\LightingCS.hlsl" />
		<EmbeddedResource Include="Shaders\Standard\TonemapCS.hlsl" />
		<EmbeddedResource Include="Shaders\Standard\MaterialCS.hlsl" />
		<EmbeddedResource Include="Shaders\Standard\PickCS.hlsl" />
		<EmbeddedResource Include="Shaders\Standard\Prepass\BaseVS.hlsl" />
		<EmbeddedResource Include="Shaders\Common\Gizmos\GeomMS.hlsl" />
		<EmbeddedResource Include="Shaders\Common\Gizmos\Gizmos.h" />
		<EmbeddedResource Include="Shaders\Common\Gizmos\GizmosPS.hlsl" />
		<EmbeddedResource Include="Shaders\Common\Gizmos\LineMS.hlsl" />
		<EmbeddedResource Include="Shaders\Common.h" />
		<EmbeddedResource Include="Shaders\World.h" />
		<EmbeddedResource Include="Shaders\Lighting.h" />
		<EmbeddedResource Include="Shaders\Standard\CullCS.hlsl" />
		<EmbeddedResource Include="Shaders\Standard\Bin\BinCountCS.hlsl" />
		<EmbeddedResource Include="Shaders\Standard\Bin\BinScanCS.hlsl" />
		<EmbeddedResource Include="Shaders\Standard\Bin\BinScatterCS.hlsl" />
		<EmbeddedResource Include="Shaders\Standard\Prepass\PrepassPS.hlsl" />
		
		<None Update="Plugin.targets" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Modules\NFM.Common\NFM.Common.csproj" />
		<ProjectReference Include="..\Modules\NFM.GPU\NFM.GPU.csproj" />
	</ItemGroup>
</Project>